server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hade?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: com.example.demo.util.MySQL5TableType
    show-sql: true
